config/routes.rb
Rails.application.routes.draw do
  root 'users#new'
  get 'home/index'
  get 'signup', to: 'users#new'
  get 'accounts/index', to: 'accounts#index'
  resources :accounts, only: %i[new create]
  resources :users, only: [:create]
end

app/models/account.rb
class Account < ApplicationRecord
  belongs_to :user
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/asset.rb
class Asset < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  validates_presence_of :email
  has_many :accounts
end

app/controllers/accounts_controller.rb
# frozen_string_literal: true

class AccountsController < ApplicationController
  def index
    @accounts = Account.where({ user_id: session[:user_id] })
  end

  def show
    @account = Account.find(params[:id])
  end

  def new
    @account = Account.new({ user_id: session[:user_id] })
  end

  def create
    @account = Account.new(account_params)
    @account.user_id = session[:user_id]
    @account.save
    redirect_to '/accounts/index'
  end

  private

  def account_params
    params.require(:account).permit(:institution)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index; end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.find_or_create_by(user_params)
    session[:user_id] = @user.id
    redirect_to '/accounts/index', notice: 'Thanks for signing up!'
  end

  private

  def user_params
    params.require(:user).permit(:email)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/accounts/index.html.erb
<p class="text-xl">Accounts</p>
<div>
  <p>This is the accounts page</p>
</div>
<div>
  <%= @accounts.each do |account| %>
    <div>
      <h2 class="account-heading">
        Institution: <%= account.institution %>
      </h2>
    </div>
  <% end %>
  <div>
    <p><%= link_to "New Account", '/accounts/new' %></p>
  </div>
</div>

app/views/accounts/new.html.erb
<p>Accounts</p>
<div>
  <%= form_with model: @account, url: accounts_path, method: :post, action: "/accounts"  do |form| %>
    <h1>Add a new Account</h1>
    <%= form.text_field :institution %>
    <%= form.submit "Add Account" %>
  <% end %>
</div>

app/views/accounts/show.html.erb
<h1>
<%= @account.institution %>
</h1>

app/views/home/index.html.erb
<h1 class="text-3xl font-bold underline">Borkedfolio, Baby</h1>
<p>This is the good ish baby</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BorkedRails</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "tailwind", "inter-font", "data-turbo-track": "reload" %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <main class="container mx-auto mt-28 px-5 flex application">
      <%= yield %>
    </main>
  </body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_with model: @user, url: users_path do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% @user.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br />
    <%= f.email_field :email %>
  </div>
  <div class="actions"><%= f.submit "Sign Up" %></div>
<% end %>